version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - misspell
    - revive
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
