// Code generated by protogen. DO NOT EDIT.
//
// Mirrors the Go wire protocol (agentloop's protocol package) and the
// desktop.App command surface (internal/desktop).
// Regenerate with: go run ./tools/protogen

import { Events } from '@wailsio/runtime';
import type { AssistantDelta, ContextUsage, Envelope, HarmAutoAllow, PassportStatus, PermissionRequest, PlanRun, RecorderLevel, RecorderState, RecorderTranscript, RetryNotice, SessionRenamed, SkillInstallProgress, ToolEvent, TurnEnd, TurnError, TurnQueued, UpdateInfo, Warning } from './types';

// EventMap maps every wire event name to its payload type.
export interface EventMap {
  'assistant:delta': AssistantDelta;
  'assistant:thinking': AssistantDelta;
  'context:usage': ContextUsage;
  'harm:autoallow': HarmAutoAllow;
  'llm:retry': RetryNotice;
  'passport:changed': PassportStatus;
  'permission:request': PermissionRequest;
  'plan:updated': PlanRun;
  'recorder:level': RecorderLevel;
  'recorder:state': RecorderState;
  'recorder:transcript': RecorderTranscript;
  'session:renamed': SessionRenamed;
  'skill:install': SkillInstallProgress;
  'tool:event': ToolEvent;
  'turn:end': TurnEnd;
  'turn:error': TurnError;
  'turn:queued': TurnQueued;
  'update:status': UpdateInfo;
  'warning': Warning;
}

// onEvent subscribes to a host event and delivers its typed payload.
// It returns an unsubscribe function.
//
// Wails v3 的回调收到的是 WailsEvent 对象而不是数据本身,载荷挂在 .data 上;
// Go 侧 app.Event.Emit(name, envelope) 单参数发射时 event.Data 就是 envelope,
// 所以这里剥一层即可。
export function onEvent<K extends keyof EventMap>(name: K, cb: (payload: EventMap[K]) => void): () => void {
  return Events.On(name, (ev) => cb((ev.data as Envelope<EventMap[K]>).payload));
}

// onEnvelope subscribes to a host event and delivers the full envelope
// (sessionId, seq, ts plus the typed payload). It returns an unsubscribe function.
export function onEnvelope<K extends keyof EventMap>(name: K, cb: (env: Envelope<EventMap[K]>) => void): () => void {
  return Events.On(name, (ev) => cb(ev.data as Envelope<EventMap[K]>));
}
