// Code generated by protogen. DO NOT EDIT.
//
// Mirrors the Go wire protocol (agentloop's protocol package) and the
// desktop.App command surface (internal/desktop).
// Regenerate with: go run ./tools/protogen

// Mirrors protocol.Version. Version is the protocol's single monotonically increasing version number.
export const ProtocolVersion = 1;

// Mirrors the protocol.Event* constants. Event names emitted by the host; payload types are mapped in events.ts.
export const Events = {
  AssistantDelta: 'assistant:delta',
  AssistantThinking: 'assistant:thinking',
  HarmAutoAllow: 'harm:autoallow',
  PassportChanged: 'passport:changed',
  PermissionRequest: 'permission:request',
  Retry: 'llm:retry',
  SessionRenamed: 'session:renamed',
  ToolEvent: 'tool:event',
  TurnEnd: 'turn:end',
  TurnError: 'turn:error',
  TurnQueued: 'turn:queued',
  Warning: 'warning',
} as const;

// EventName is the union of known event names.
export type EventName = (typeof Events)[keyof typeof Events];

// Mirrors the protocol.ToolEvent* constants. Tool event types, the discriminator values of ToolEvent.type.
export const ToolEventTypes = {
  AgentDelta: 'agent_delta',
  AgentUsage: 'agent_usage',
  Completed: 'completed',
  Failed: 'failed',
  Output: 'output',
  Progress: 'progress',
  Started: 'started',
} as const;

// ToolEventType keeps unknown discriminators assignable so a newer host degrades gracefully.
export type ToolEventType = (typeof ToolEventTypes)[keyof typeof ToolEventTypes] | (string & {});

// Mirrors the protocol.Decision* constants. Decision values a client passes to resolvePermission; the host fails closed on anything else.
export const Decisions = {
  AllowOnce: 'allow-once',
  AllowProject: 'allow-project',
  AllowSession: 'allow-session',
  Deny: 'deny',
} as const;

// Decision keeps unknown values assignable; the host treats them as deny.
export type Decision = (typeof Decisions)[keyof typeof Decisions] | (string & {});

// Mirrors the protocol.ErrCode* constants. Error codes carried by protocol.Error; clients switch on code.
export const ErrCodes = {
  Busy: 'busy',
  Internal: 'internal',
  InvalidArgument: 'invalid_argument',
  NoSession: 'no_session',
  NotFound: 'not_found',
  NotLoggedIn: 'not_logged_in',
  Unavailable: 'unavailable',
} as const;

// ErrCode keeps unknown codes assignable so a newer host degrades gracefully.
export type ErrCode = (typeof ErrCodes)[keyof typeof ErrCodes] | (string & {});

// Mirrors protocol.AgentInfo. AgentInfo is one sub-agent for the UI's sub-agent manager.
export interface AgentInfo {
  name: string;
  description: string;
  tools: string;
  model: string;
  prompt: string;
  source: string;
  path: string;
  editable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.AgentList. AgentList is the sub-agent manager's view: loaded agents plus load problems.
export interface AgentList {
  agents: AgentInfo[] | null;
  problems: AgentProblem[] | null;
}

// Mirrors protocol.AgentProblem. AgentProblem reports a sub-agent file that failed to load.
export interface AgentProblem {
  path: string;
  reason: string;
}

// Mirrors protocol.AgentSaveRequest. AgentSaveRequest creates or updates a sub-agent.
export interface AgentSaveRequest {
  originalName: string;
  name: string;
  description: string;
  tools: string;
  model: string;
  prompt: string;
  scope: string;
}

// Mirrors protocol.ApprovalSummary. ApprovalSummary is the display-oriented classification of an action awaiting approval.
export interface ApprovalSummary {
  toolName?: string;
  operation?: string;
  risk?: string;
  resourceTypes?: string[] | null;
  resourceScope?: string;
  resourceCount?: number;
  mutationKind?: string;
  commandCategory?: string;
  commandSummary?: string;
  networkHost?: string;
  mcpServer?: string;
  mcpTool?: string;
  policyRule?: string;
}

// Mirrors protocol.AssistantDelta. AssistantDelta is one streamed text fragment from the model.
export interface AssistantDelta {
  text: string;
}

// Mirrors protocol.CompactResult. CompactResult reports the in-memory message counts before and after an explicit compaction.
export interface CompactResult {
  before: number;
  after: number;
  contextTokens: number;
  inputTokens: number;
  outputTokens: number;
}

// Mirrors protocol.CustomModel. CustomModel 是用户自定义的直连模型接入点，与通行证平台模型并列显示在模型 选择器里。Provider 是引擎 provider registry 的名称（当前为 openai/anthropic）； 旧配置没有该字段时由桌面端按 openai 兼容处理。密钥字段仅用于桌面端持久化， ListCustomModels 对外返回时必须清空，只通过 HasAPIKey 暴露是否已配置。
export interface CustomModel {
  name: string;
  provider?: string;
  model: string;
  baseURL: string;
  hasAPIKey?: boolean;
  apiKey?: string;
  apiKeyProtected?: string;
}

// Mirrors protocol.EditDiff. EditDiff is the red/green review of one edit: the turn baseline vs the turn's latest content for that file, as renderable diff lines.
export interface EditDiff {
  relPath: string;
  created: boolean;
  lines: OutputLine[] | null;
}

// Mirrors protocol.EditRecord. EditRecord is the per-edit metadata attached to a Write/Edit tool event's Data (live) and returned by ListEdits (resume).
export interface EditRecord {
  snapshotId: string;
  toolUseId: string;
  relPath: string;
  added: number;
  removed: number;
  created: boolean;
  reverted?: boolean;
}

// Mirrors protocol.Envelope. Envelope wraps every event on the wire with its addressing and ordering metadata, so the same event stream works over any transport: in-process bindings today, a multiplexed WebSocket tomorrow.
export interface Envelope<P = unknown> {
  event: string;
  sessionId?: string;
  seq: number;
  ts: string;
  payload: P;
}

// Mirrors protocol.Error. Error is the wire form of a command failure.
export interface Error {
  code: ErrCode;
  message: string;
  details?: Record<string, string> | null;
}

// Mirrors protocol.FileReference. FileReference is a sanitized, workspace-relative file reference for UI progress summaries.
export interface FileReference {
  path: string;
  kind?: string;
}

// Mirrors protocol.HarmAutoAllow. HarmAutoAllow is the payload of EventHarmAutoAllow: a sanitized record of a harm-gate decision (no raw command or path).
export interface HarmAutoAllow {
  tool: string;
  toolUseID: string;
  operation: string;
  risk: string;
  reason: string;
  outcome: string;
  count: number;
}

// Mirrors protocol.Info. Info is the handshake payload describing the host's protocol support.
export interface Info {
  protocolVersion: number;
  appVersion?: string;
}

// Mirrors protocol.MCPServerInfo. MCPServerInfo is one configured MCP server plus its live connection state, for the UI's MCP management page.
export interface MCPServerInfo {
  name: string;
  transport: string;
  command?: string;
  args?: string[] | null;
  env?: Record<string, string> | null;
  dir?: string;
  url?: string;
  headers?: Record<string, string> | null;
  enabled: boolean;
  connected: boolean;
  toolCount: number;
}

// Mirrors protocol.MCPServerInput. MCPServerInput is the payload for creating or updating a server.
export interface MCPServerInput {
  originalName: string;
  name: string;
  transport: string;
  command: string;
  args: string[] | null;
  env: Record<string, string> | null;
  dir: string;
  url: string;
  headers: Record<string, string> | null;
  enabled: boolean;
}

// Mirrors protocol.MemoryInfo. MemoryInfo is the agent's persistent memory, split by scope.
export interface MemoryInfo {
  user: string[] | null;
  project: string[] | null;
}

// Mirrors protocol.OutputLine. OutputLine is a single sanitized, bounded line of tool output for UI display.
export interface OutputLine {
  stream?: string;
  text: string;
}

// Mirrors protocol.PassportModel. PassportModel 是 Bridge /v1/models 列表项。
export interface PassportModel {
  id: string;
  ownedBy: string;
}

// Mirrors protocol.PassportStatus. PassportStatus 是前端展示用的登录态 + 用户信息。
export interface PassportStatus {
  loggedIn: boolean;
  userId?: string;
  userName?: string;
  name?: string;
  nickname?: string;
  avatar?: string;
  tenantId?: string;
}

// Mirrors protocol.PassportTenant. PassportTenant 是当前用户可用的租户（Bridge /api/tenants）。 ParentID 供前端渲染层级树；父租户可能不在用户的可用列表里 （用户只被授了子级），前端须把这类节点当根渲染，不能丢弃。
export interface PassportTenant {
  id: string;
  name: string;
  parentId?: string;
}

// Mirrors protocol.PermissionRequest. PermissionRequest asks the user to approve or deny one pending action.
export interface PermissionRequest {
  id: string;
  summary: ApprovalSummary;
  targets?: string[] | null;
  command?: string;
  harmReason?: string;
  samplingServer?: string;
}

// Mirrors protocol.ProjectContextInfo. ProjectContextInfo is the workspace's project-instructions file (RUNCODE.md or CLAUDE.md), for viewing and editing.
export interface ProjectContextInfo {
  path: string;
  name: string;
  content: string;
  exists: boolean;
}

// Mirrors protocol.ResultImage. ResultImage is an inline image a tool returned (Data is base64 in JSON).
export interface ResultImage {
  media_type?: string;
  data?: string;
  url?: string;
}

// Mirrors protocol.ResumedBlock. ResumedBlock is one rendered item of a reopened conversation.
export interface ResumedBlock {
  kind: string;
  text?: string;
  tool?: ResumedTool;
}

// Mirrors protocol.ResumedSession. ResumedSession carries a reopened session's status plus its prior conversation as rendered blocks so the frontend can repaint it.
export interface ResumedSession {
  info: SessionInfo;
  blocks: ResumedBlock[] | null;
  contextTokens: number;
}

// Mirrors protocol.ResumedTool. ResumedTool is a reconstructed tool step.
export interface ResumedTool {
  toolName: string;
  toolUseId: string;
  path?: string;
  input?: string;
  isError: boolean;
  output?: string;
}

// Mirrors protocol.RetryNotice. RetryNotice reports that an LLM request failed transiently and is being retried.
export interface RetryNotice {
  reason: string;
  attempt: number;
  maxAttempts: number;
}

// Mirrors protocol.SaveCustomModelRequest. SaveCustomModelRequest 新增或修改一个自定义模型。编辑时 OriginalName 定位旧 记录；APIKey 留空表示保留旧密钥，ClearAPIKey 才显式清除，两者不能同时使用。
export interface SaveCustomModelRequest {
  originalName?: string;
  name: string;
  provider?: string;
  model: string;
  baseURL: string;
  apiKey?: string;
  clearAPIKey?: boolean;
}

// Mirrors protocol.SessionInfo. SessionInfo is the display state returned when a session starts and by Status.
export interface SessionInfo {
  sessionId: string;
  model: string;
  cwd: string;
  permissionMode: string;
  planMode: boolean;
  reasoningScenario: string;
  thinkingEffort: string;
  maxContextTokens: number;
  inputPricePerMTok: number;
  outputPricePerMTok: number;
  pricingSource: string;
  previewBaseURL: string;
}

// Mirrors protocol.SessionRenamed. SessionRenamed announces a session's freshly generated title.
export interface SessionRenamed {
  id: string;
  title: string;
}

// Mirrors protocol.SessionSummary. SessionSummary describes a saved session for the sidebar's recent list.
export interface SessionSummary {
  id: string;
  title: string;
  when: string;
  turns: number;
}

// Mirrors protocol.SkillInfo. SkillInfo is one project skill for the UI's skill manager.
export interface SkillInfo {
  name: string;
  description: string;
  body: string;
  source: string;
  path: string;
  editable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.SkillList. SkillList is the skill manager's view: loaded skills plus load problems.
export interface SkillList {
  skills: SkillInfo[] | null;
  problems: SkillProblem[] | null;
}

// Mirrors protocol.SkillProblem. SkillProblem reports a skill directory that failed to load.
export interface SkillProblem {
  dir: string;
  reason: string;
}

// Mirrors protocol.SkillSaveRequest. SkillSaveRequest creates or updates a skill.
export interface SkillSaveRequest {
  originalName: string;
  name: string;
  description: string;
  body: string;
  scope: string;
}

// Mirrors protocol.StartSessionRequest. StartSessionRequest opens a session for a workspace.
export interface StartSessionRequest {
  cwd: string;
  provider: string;
  model: string;
  customModelName?: string;
  tenantId: string;
  baseURL: string;
  apiKey: string;
  authToken: string;
  apiKeyProtected?: string;
  authTokenProtected?: string;
  permissionMode: string;
  reasoningScenario: string;
  thinkingEffort: string;
  harmJudgeModel: string;
  harmJudgeVotes: number;
  maxTokens: number;
  maxContextTokens: number;
  maxHistoryMessages: number;
  resume: string;
  continue: boolean;
  recentWorkspaces?: string[] | null;
  customModels?: CustomModel[] | null;
  webProxy?: string;
}

// Mirrors protocol.ToolEvent. ToolEvent is the wire form of one tool-lifecycle update.
export interface ToolEvent {
  type: ToolEventType;
  toolName?: string;
  toolUseID?: string;
  parentToolUseID?: string;
  agentName?: string;
  input?: unknown;
  message?: string;
  data?: unknown;
  files?: FileReference[] | null;
  filesTotal?: number;
  output?: OutputLine[] | null;
  outputTotal?: number;
  outputTruncated?: boolean;
  image?: ResultImage;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

// Mirrors protocol.ToolInfo. ToolInfo is a tool's name and description for the @-mention picker.
export interface ToolInfo {
  name: string;
  description: string;
  source: string;
  server?: string;
  concurrencySafe: boolean;
  toggleable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.TurnEnd. TurnEnd summarizes a completed turn.
export interface TurnEnd {
  text: string;
  stopReason: string;
  iterations: number;
  toolResultCount: number;
  inputTokens: number;
  outputTokens: number;
  contextTokens: number;
  stopped: boolean;
  durationMs?: number;
}

// Mirrors protocol.TurnError. TurnError reports a failed or interrupted turn.
export interface TurnError {
  error: string;
}

// Mirrors protocol.TurnQueued. TurnQueued announces that a submitted turn is waiting for a concurrency slot.
export interface TurnQueued {
}

// Mirrors protocol.Warning. Warning is a non-fatal diagnostic surfaced to the UI.
export interface Warning {
  message: string;
}
