// Code generated by protogen. DO NOT EDIT.
//
// Mirrors the Go wire protocol (agentloop's protocol package) and the
// desktop.App command surface (internal/desktop).
// Regenerate with: go run ./tools/protogen

// Mirrors protocol.Version. Version is the protocol's single monotonically increasing version number.
export const ProtocolVersion = 1;

// Mirrors the protocol.Event* constants. Event names emitted by the host; payload types are mapped in events.ts.
export const Events = {
  AskpassDone: 'askpass:done',
  AskpassRequest: 'askpass:request',
  AssistantDelta: 'assistant:delta',
  AssistantThinking: 'assistant:thinking',
  ContextUsage: 'context:usage',
  HarmAutoAllow: 'harm:autoallow',
  OABlocked: 'oa:blocked',
  PassportChanged: 'passport:changed',
  PermissionRequest: 'permission:request',
  PlanUpdated: 'plan:updated',
  RecorderLevel: 'recorder:level',
  RecorderState: 'recorder:state',
  RecorderTranscript: 'recorder:transcript',
  Retry: 'llm:retry',
  Runtimes: 'runtimes:status',
  SessionRenamed: 'session:renamed',
  SessionStatus: 'session:status',
  SkillInstall: 'skill:install',
  ToolEvent: 'tool:event',
  TurnEnd: 'turn:end',
  TurnError: 'turn:error',
  TurnQueued: 'turn:queued',
  Update: 'update:status',
  Warning: 'warning',
} as const;

// EventName is the union of known event names.
export type EventName = (typeof Events)[keyof typeof Events];

// Mirrors the protocol.ToolEvent* constants. Tool event types, the discriminator values of ToolEvent.type.
export const ToolEventTypes = {
  AgentDelta: 'agent_delta',
  AgentUsage: 'agent_usage',
  Completed: 'completed',
  Failed: 'failed',
  Output: 'output',
  Progress: 'progress',
  Started: 'started',
} as const;

// ToolEventType keeps unknown discriminators assignable so a newer host degrades gracefully.
export type ToolEventType = (typeof ToolEventTypes)[keyof typeof ToolEventTypes] | (string & {});

// Mirrors the protocol.Decision* constants. Decision values a client passes to resolvePermission; the host fails closed on anything else.
export const Decisions = {
  AllowOnce: 'allow-once',
  AllowProject: 'allow-project',
  AllowSession: 'allow-session',
  Deny: 'deny',
} as const;

// Decision keeps unknown values assignable; the host treats them as deny.
export type Decision = (typeof Decisions)[keyof typeof Decisions] | (string & {});

// Mirrors the protocol.ErrCode* constants. Error codes carried by protocol.Error; clients switch on code.
export const ErrCodes = {
  Busy: 'busy',
  Internal: 'internal',
  InvalidArgument: 'invalid_argument',
  NoSession: 'no_session',
  NotFound: 'not_found',
  NotLoggedIn: 'not_logged_in',
  Unavailable: 'unavailable',
} as const;

// ErrCode keeps unknown codes assignable so a newer host degrades gracefully.
export type ErrCode = (typeof ErrCodes)[keyof typeof ErrCodes] | (string & {});

// Mirrors the protocol.PlanStage* constants. Stages of 计划模式's planning pipeline, in order; the values of plan_write's stage argument.
export const PlanStages = {
  Design: 'design',
  Review: 'review',
  Understanding: 'understanding',
} as const;

// PlanStage is the closed set of planning stages — the shell's own pipeline, so an unknown value is a bug, not a newer peer.
export type PlanStage = (typeof PlanStages)[keyof typeof PlanStages];

// Mirrors the protocol.PlanState* constants. Lifecycle states of a planning run, carried by PlanRun.state.
export const PlanStates = {
  AwaitingApproval: 'awaiting_approval',
  Cancelled: 'cancelled',
  Executing: 'executing',
  Idle: 'idle',
  Planning: 'planning',
} as const;

// PlanState is the closed set of planning-run states.
export type PlanState = (typeof PlanStates)[keyof typeof PlanStates];

// Mirrors the protocol.SkillInstall* constants. Stages of installing a market skill, in order; the values of SkillInstallProgress.stage.
export const SkillInstallStages = {
  Detail: 'detail',
  Done: 'done',
  Download: 'download',
  Extract: 'extract',
  Verify: 'verify',
} as const;

// SkillInstallStage is the closed set of install stages — the shell drives this pipeline itself, so an unknown value is a bug, not a newer peer.
export type SkillInstallStage = (typeof SkillInstallStages)[keyof typeof SkillInstallStages];

// Mirrors the protocol.Update* constants. Stages of the version updater; the values of UpdateInfo.stage.
export const UpdateStages = {
  Available: 'available',
  Checking: 'checking',
  Downloading: 'downloading',
  Failed: 'failed',
  Idle: 'idle',
  Latest: 'latest',
  Ready: 'ready',
  Verifying: 'verifying',
} as const;

// UpdateStage is the closed set of updater stages — the shell drives this state machine itself, so an unknown value is a bug, not a newer peer.
export type UpdateStage = (typeof UpdateStages)[keyof typeof UpdateStages];

// Mirrors the protocol.RuntimePack* constants. Ids of the managed runtime packs (Python / Node / Git); the values of RuntimePack.id.
export const RuntimePackIds = {
  Git: 'git',
  Node: 'node',
  Python: 'python',
} as const;

// RuntimePackId is the closed set of runtime packs — the shell decides what a pack means (layout, probe), so an unknown id is a bug, not a newer peer.
export type RuntimePackId = (typeof RuntimePackIds)[keyof typeof RuntimePackIds];

// Mirrors the protocol.RuntimeStage* constants. Install stages of one managed runtime pack; the values of RuntimePack.stage.
export const RuntimeStages = {
  Absent: 'absent',
  Authorizing: 'authorizing',
  Downloading: 'downloading',
  Extracting: 'extracting',
  Failed: 'failed',
  Ready: 'ready',
  Verifying: 'verifying',
} as const;

// RuntimeStage is the closed set of install stages — the shell drives this pipeline itself, so an unknown value is a bug, not a newer peer.
export type RuntimeStage = (typeof RuntimeStages)[keyof typeof RuntimeStages];

// Mirrors protocol.AgentInfo. AgentInfo is one sub-agent for the UI's sub-agent manager.
export interface AgentInfo {
  name: string;
  description: string;
  tools: string;
  model: string;
  prompt: string;
  source: string;
  path: string;
  editable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.AgentList. AgentList is the sub-agent manager's view: loaded agents plus load problems.
export interface AgentList {
  agents: AgentInfo[] | null;
  problems: AgentProblem[] | null;
}

// Mirrors protocol.AgentProblem. AgentProblem reports a sub-agent file that failed to load.
export interface AgentProblem {
  path: string;
  reason: string;
}

// Mirrors protocol.AgentSaveRequest. AgentSaveRequest creates or updates a sub-agent.
export interface AgentSaveRequest {
  originalName: string;
  name: string;
  description: string;
  tools: string;
  model: string;
  prompt: string;
  scope: string;
}

// Mirrors protocol.ApprovalSummary. ApprovalSummary is the display-oriented classification of an action awaiting approval.
export interface ApprovalSummary {
  toolName?: string;
  operation?: string;
  risk?: string;
  resourceTypes?: string[] | null;
  resourceScope?: string;
  resourceCount?: number;
  mutationKind?: string;
  outsideWorkspace?: boolean;
  commandCategory?: string;
  commandSummary?: string;
  networkHost?: string;
  mcpServer?: string;
  mcpTool?: string;
  policyRule?: string;
}

// Mirrors protocol.AskpassDone. AskpassDone 撤回一次请求。
export interface AskpassDone {
  id: string;
}

// Mirrors protocol.AskpassRequest. AskpassRequest 是一次"sudo 要密码"。
export interface AskpassRequest {
  id: string;
  sessionId: string;
  command: string;
  prompt: string;
  purpose?: string;
}

// Mirrors protocol.AssistantDelta. AssistantDelta is one streamed text fragment from the model.
export interface AssistantDelta {
  text: string;
}

// Mirrors protocol.CodexDeviceCode. CodexDeviceCode 是发起登录后要展示给用户的东西：把 UserCode 显示出来，让他在 VerificationURL 那个页面里输入。ExpiresAt 之后这串码作废，要重新发起。
export interface CodexDeviceCode {
  userCode: string;
  verificationUrl: string;
  expiresAt: string;
}

// Mirrors protocol.CodexModel. CodexModel 是 ChatGPT 账号下可用的一个 Codex 模型。清单由上游给出，不是本地 写死的表——可用模型按账号与订阅档次变化。
export interface CodexModel {
  id: string;
  displayName?: string;
  description?: string;
}

// Mirrors protocol.CodexStatus. CodexStatus 是 ChatGPT 账号的登录态。未登录时 LoggedIn=false，其余字段为空。
export interface CodexStatus {
  loggedIn: boolean;
  email?: string;
  accountId?: string;
}

// Mirrors protocol.CompactResult. CompactResult reports the in-memory message counts before and after an explicit compaction.
export interface CompactResult {
  before: number;
  after: number;
  contextTokens: number;
  inputTokens: number;
  outputTokens: number;
}

// Mirrors protocol.ContextAuditInfo. ContextAuditInfo 是"上下文审核"（仅测试版构建存在）的状态快照。开启后，引擎每次 发给模型的完整请求上下文（系统提示词、全部消息历史、工具清单）都会落盘，并由一个 仅监听 127.0.0.1 的本地页面提供查看。
export interface ContextAuditInfo {
  supported: boolean;
  enabled: boolean;
  url: string;
  dir: string;
}

// Mirrors protocol.ContextUsage. ContextUsage reports how full the context window is right now, emitted before each model round-trip inside a turn.
export interface ContextUsage {
  contextTokens: number;
  maxContextTokens: number;
  iteration: number;
}

// Mirrors protocol.CustomModel. CustomModel 是用户自定义的直连模型接入点，与通行证平台模型并列显示在模型 选择器里。Provider 通常是引擎 provider registry 的名称（openai/ openai-responses/anthropic），由 llm.IsRegistered 校验而非本仓库的名单；旧配置 没有该字段时由桌面端按 openai 兼容处理。 唯一的例外是 "codex"：它是**外壳层**的服务商，引擎注册表里没有这个名字。 桌面端在解析时把它翻译成 openai-responses（Codex 说的就是 Responses 协议）， 并把 Base URL 指向本地那个负责补凭据与指纹头的小代理，见 internal/codexproxy。密钥字段仅用于桌面端持久化， ListCustomModels 对外返回时必须清空，只通过 HasAPIKey 暴露是否已配置。
export interface CustomModel {
  name: string;
  provider?: string;
  model: string;
  baseURL: string;
  hasAPIKey?: boolean;
  authMode?: string;
  apiKey?: string;
  apiKeyProtected?: string;
}

// Mirrors protocol.EditDiff. EditDiff is the red/green review of one edit: the turn baseline vs the turn's latest content for that file, as renderable diff lines.
export interface EditDiff {
  relPath: string;
  created: boolean;
  lines: OutputLine[] | null;
}

// Mirrors protocol.EditRecord. EditRecord is the per-edit metadata attached to a Write/Edit tool event's Data (live) and returned by ListEdits (resume).
export interface EditRecord {
  snapshotId: string;
  toolUseId: string;
  relPath: string;
  added: number;
  removed: number;
  created: boolean;
  reverted?: boolean;
}

// Mirrors protocol.Envelope. Envelope wraps every event on the wire with its addressing and ordering metadata, so the same event stream works over any transport: in-process bindings today, a multiplexed WebSocket tomorrow.
export interface Envelope<P = unknown> {
  event: string;
  sessionId?: string;
  seq: number;
  ts: string;
  payload: P;
}

// Mirrors protocol.Error. Error is the wire form of a command failure.
export interface Error {
  code: ErrCode;
  message: string;
  details?: Record<string, string> | null;
}

// Mirrors protocol.FileReference. FileReference is a sanitized, workspace-relative file reference for UI progress summaries.
export interface FileReference {
  path: string;
  kind?: string;
}

// Mirrors protocol.HarmAutoAllow. HarmAutoAllow is the payload of EventHarmAutoAllow: a sanitized record of a harm-gate decision (no raw command or path).
export interface HarmAutoAllow {
  tool: string;
  toolUseID: string;
  operation: string;
  risk: string;
  reason: string;
  outcome: string;
  count: number;
}

// Mirrors protocol.Info. Info is the handshake payload describing the host's protocol support.
export interface Info {
  protocolVersion: number;
  appVersion?: string;
}

// Mirrors protocol.MCPServerInfo. MCPServerInfo is one configured MCP server plus its live connection state, for the UI's MCP management page.
export interface MCPServerInfo {
  name: string;
  transport: string;
  command?: string;
  args?: string[] | null;
  env?: Record<string, string> | null;
  dir?: string;
  url?: string;
  headers?: Record<string, string> | null;
  passport: boolean;
  enabled: boolean;
  connected: boolean;
  toolCount: number;
  tools?: MCPToolBrief[] | null;
}

// Mirrors protocol.MCPServerInput. MCPServerInput is the payload for creating or updating a server.
export interface MCPServerInput {
  originalName: string;
  name: string;
  transport: string;
  command: string;
  args: string[] | null;
  env: Record<string, string> | null;
  dir: string;
  url: string;
  headers: Record<string, string> | null;
  passport: boolean;
  enabled: boolean;
}

// Mirrors protocol.MCPToolBrief. MCPToolBrief is one tool a connected MCP server exposes, for listing a server's capabilities on the MCP page.
export interface MCPToolBrief {
  name: string;
  description?: string;
}

// Mirrors protocol.MarketSkill. MarketSkill 是技能市场（lea-config / lea-gateway）里的一条。 与本包里其它 DTO 一样，它是**桌面自己的线上形状**，不是上游 API 的原样转发： 上游返回 snake_case 且带一堆界面用不到的列（is_builtin / can_edit / pending_publish / system_prompt 全文 …），照抄进前端只会让市场页跟着上游的表结构 走。这里只留画得出来、装得上的那几个字段，上游加列不必动前端。
export interface MarketSkill {
  id: number;
  name: string;
  displayName: string;
  description: string;
  category: string;
  version: string;
  allowedTools: string[] | null;
  hasBundle: boolean;
  installedUser: boolean;
  installedProject: boolean;
}

// Mirrors protocol.McpMarketEntry. McpMarketEntry is one installable MCP server from the platform market (bridge GET /api/mcp/market).
export interface McpMarketEntry {
  id: string;
  name: string;
  description?: string;
  transport: string;
  url: string;
  passport: boolean;
  official: boolean;
}

// Mirrors protocol.MemoryInfo. MemoryInfo is the agent's persistent memory, split by scope.
export interface MemoryInfo {
  user: string[] | null;
  project: string[] | null;
}

// Mirrors protocol.OABlocked. OABlocked 说明某一次工具调用被"OA 数据只进本地模型"的闸门拦下了，而且外壳已经 排好自动切换。 它只为界面呈现而生：那次调用在模型眼里是失败的（工具结果带 IsError，模型要据此 停下来），但对用户不是——系统正在自动恢复，这一轮随后会被本地模型整个重跑。 界面据此把那张工具卡从红色的"执行失败"改写成中性的"已阻止 · 正在切换"。
export interface OABlocked {
  toolUseId: string;
  localModel: string;
}

// Mirrors protocol.OpenSessionInfo. OpenSessionInfo 描述**此刻开着**的一条会话，供界面画会话列表。 与 SessionSummary 的分工：那个是工作区里**存下来**的历史会话（标题、时间、 回合数），这个是当前进程里活着的会话。界面上是两栏：「打开中」与「历史」。 只带后端独有的事实。标题走 session:renamed 事件与 SessionSummary，待审批数在 前端的授权队列里——都不必在这里重复一遍，重复就会出现两个版本互相矛盾。
export interface OpenSessionInfo {
  sessionId: string;
  workspace: string;
  running: boolean;
  focused: boolean;
}

// Mirrors protocol.OutputLine. OutputLine is a single sanitized, bounded line of tool output for UI display.
export interface OutputLine {
  stream?: string;
  text: string;
}

// Mirrors protocol.PassportModel. PassportModel 是 Bridge /v1/models 列表项。 Local 及其后两个字段是本产品对 OpenAI 模型清单的扩展，由基座的 bridge.catalog 下发（改 ConfigMap 即生效，客户端不必发版）: - Local 标记该模型的推理在内网完成。**客户端只认这个标记、不做二次判断**—— "这个 id 的渠道到底指向哪里"只有基座知道，把它写死在客户端等于让两处事实 互相漂移。标记错了的后果是保密数据出内网，所以基座那边要在配置旁写明依据。 - LocalDefault 指定 Local 模型里默认用哪一个。只标 Local 不够:清单顺序一变 就换了模型，而"换哪个模型"必须是显式声明。 - ContextTokens 是该模型的上下文窗口。本地模型的窗口通常远小于云端模型， 切过去时要按它重设会话预算，否则历史一长第一次请求就超限。0 = 未声明， 沿用会话原值。
export interface PassportModel {
  id: string;
  ownedBy: string;
  local?: boolean;
  localDefault?: boolean;
  contextTokens?: number;
}

// Mirrors protocol.PassportStatus. PassportStatus 是前端展示用的登录态 + 用户信息。
export interface PassportStatus {
  loggedIn: boolean;
  userId?: string;
  userName?: string;
  name?: string;
  nickname?: string;
  avatar?: string;
  tenantId?: string;
}

// Mirrors protocol.PassportTenant. PassportTenant 是当前用户可用的租户（Bridge /api/tenants）。 ParentID 供前端渲染层级树；父租户可能不在用户的可用列表里 （用户只被授了子级），前端须把这类节点当根渲染，不能丢弃。
export interface PassportTenant {
  id: string;
  name: string;
  parentId?: string;
}

// Mirrors protocol.PermissionRequest. PermissionRequest asks the user to approve or deny one pending action.
export interface PermissionRequest {
  id: string;
  summary: ApprovalSummary;
  targets?: string[] | null;
  externalTargets?: string[] | null;
  externalRoots?: string[] | null;
  command?: string;
  harmReason?: string;
  samplingServer?: string;
  allowedDecisions?: string[] | null;
}

// Mirrors protocol.PlanApproveRequest. PlanApproveRequest 是用户点"确认执行"时提交的东西：编辑后的最终清单，加上执行阶段 要切换到的权限模式（沿用原先那张三选一卡片的语义：交互 / 智能）。
export interface PlanApproveRequest {
  doc: PlanDoc;
  permissionMode: string;
}

// Mirrors protocol.PlanApproveResult. PlanApproveResult 把审批的两件后果一起带回前端：会话状态已变（计划模式关、权限模式 切好），以及应当作为下一条消息发出去的执行指令。指令由后端拼是为了让措辞与清单编号 只有一个来源（也便于单测），发送仍走前端既有的 send 路径，这样 busy、用户气泡、回合 生命周期全部复用原有链路。
export interface PlanApproveResult {
  info: SessionInfo;
  executionPrompt: string;
}

// Mirrors protocol.PlanDoc. PlanDoc 是规划文档本身：三个阶段各自往里填一部分，用户在审批前还能改。
export interface PlanDoc {
  goal?: string;
  nonGoals?: string[] | null;
  title?: string;
  steps?: PlanStep[] | null;
  risks?: string[] | null;
  questions?: string[] | null;
  reviewNotes?: string[] | null;
}

// Mirrors protocol.PlanRun. PlanRun 是一次规划运行的完整对外状态，EventPlanUpdated 与 PlanStatus 都发它。
export interface PlanRun {
  state: PlanState;
  stage?: PlanStage;
  doc?: PlanDoc;
  edited?: boolean;
  updatedAt?: string;
}

// Mirrors protocol.PlanStep. PlanStep 是清单里的一步。ID 由外壳分配并在编辑往返中保持稳定（前端拿它做 key， 后端拿它认"这步是不是新加的"）；模型不提供 ID，新步骤留空由后端补。
export interface PlanStep {
  id: string;
  title: string;
  detail?: string;
  files?: string[] | null;
}

// Mirrors protocol.ProjectContextInfo. ProjectContextInfo is the workspace's project-instructions file (RUNCODE.md or AGENT.md), for viewing and editing.
export interface ProjectContextInfo {
  path: string;
  name: string;
  content: string;
  exists: boolean;
}

// Mirrors protocol.RecorderDevice. RecorderDevice 是「麦克风 ∨」下拉里的一项。
export interface RecorderDevice {
  id: string;
  name: string;
  isDefault: boolean;
}

// Mirrors protocol.RecorderDeviceList. RecorderDeviceList 是两路音源各自可选的设备。 Supported=false 表示这台机器上根本开不了录音（非 Windows、或 WASAPI 初始化 失败）。分开报而不是直接返回 error：界面要把「录音纪要」入口置灰并给出理由， 而不是等用户点下去才弹一个错。
export interface RecorderDeviceList {
  mic: RecorderDevice[] | null;
  sys: RecorderDevice[] | null;
  supported: boolean;
  reason?: string;
}

// Mirrors protocol.RecorderLevel. RecorderLevel 是两条轨的实时电平（0..1），约 20 Hz。 两条轨合成一条事件发：它们各自约 20 Hz，分开发就是 40 次/秒的事件，而界面 上是同一次重绘要用的两个数。
export interface RecorderLevel {
  mic: number;
  sys: number;
}

// Mirrors protocol.RecorderSettings. RecorderSettings 是录音纪要的客户端设置，落在配置目录里，与会话无关。
export interface RecorderSettings {
  gatewayUrl: string;
  gatewayToken: string;
  speakerName: string;
  lang: string;
  micDiarize: boolean;
  micDeviceId: string;
  sysDeviceId: string;
  keepAudio: boolean;
  autoFullMinutes: boolean;
  summaryModel: string;
  root?: string;
  version: number;
}

// Mirrors protocol.RecorderState. RecorderState 是录音状态的变化。
export interface RecorderState {
  id: string;
  state: string;
  audioMs: number;
  uplink?: string;
  error?: string;
}

// Mirrors protocol.RecorderTrack. RecorderTrack 是一条音轨录完后的记录。
export interface RecorderTrack {
  source: string;
  wav: string;
  sampleRate: number;
  channels: number;
  durationMs: number;
  gapMs: number;
  sentFrames: number;
  droppedFrames: number;
  reconnects: number;
}

// Mirrors protocol.RecorderTranscript. RecorderTranscript 是网关下行的一条转写事件。 字段与 recorder.Event 一一对应，含义见那边——这里刻意不复述，两处各写一遍 只会各自漂移。
export interface RecorderTranscript {
  type: string;
  track?: string;
  seg: number;
  rev: number;
  text?: string;
  bt?: number;
  et?: number;
  spk?: string;
  name?: string;
  userId?: string;
  conf?: number;
  segs?: number[] | null;
  silence?: number;
  need?: number;
  stage?: string;
  queuePos?: number;
}

// Mirrors protocol.RecordingInfo. RecordingInfo 是一场录音在界面上的样子。ID 为空表示「当前没有录音」。
export interface RecordingInfo {
  id: string;
  title: string;
  room: string;
  state: string;
  lang?: string;
  startedAt: string;
  endedAt?: string;
  audioMs: number;
  interrupted?: boolean;
  transcript?: string;
  needsBackfill?: boolean;
  tracks?: RecorderTrack[] | null;
  uplink?: string;
  dir?: string;
}

// Mirrors protocol.ResultImage. ResultImage is an inline image a tool returned (Data is base64 in JSON).
export interface ResultImage {
  media_type?: string;
  data?: string;
  url?: string;
}

// Mirrors protocol.ResumedBlock. ResumedBlock is one rendered item of a reopened conversation.
export interface ResumedBlock {
  kind: string;
  text?: string;
  tool?: ResumedTool;
}

// Mirrors protocol.ResumedSession. ResumedSession carries a reopened session's status plus its prior conversation as rendered blocks so the frontend can repaint it.
export interface ResumedSession {
  info: SessionInfo;
  blocks: ResumedBlock[] | null;
  contextTokens: number;
}

// Mirrors protocol.ResumedTool. ResumedTool is a reconstructed tool step.
export interface ResumedTool {
  toolName: string;
  toolUseId: string;
  path?: string;
  input?: string;
  isError: boolean;
  output?: string;
}

// Mirrors protocol.RetryNotice. RetryNotice reports that an LLM request failed transiently and is being retried.
export interface RetryNotice {
  reason: string;
  attempt: number;
  maxAttempts: number;
}

// Mirrors protocol.RuntimeInfo. RuntimeInfo 是运行时环境的完整状态，也是唯一的对外形状。 它同时是 RuntimeStatus()（纯读，不联网）的返回值和 EventRuntimes 的载荷。
export interface RuntimeInfo {
  platform: string;
  packs: RuntimePack[] | null;
  fetched: boolean;
  error: string;
}

// Mirrors protocol.RuntimeManifest. RuntimeManifest 是清单响应：这个平台上有哪些包可装。 GET {Bridge}/api/app/runtimes?product=xrun&platform=windows/amd64 为什么这一份 wire 类型是公开的、而版本更新那份（releaseWire）是私有的：清单 在本仓有**两个**消费者——客户端解析它，tools/runtimepacks 生成它。两处各写一遍 结构体，迟早有一天字段名对不上，而那种错只在装机之后才显形。放在这里，两边 编译期就绑住了。
export interface RuntimeManifest {
  platform: string;
  packs: RuntimeManifestPack[] | null;
}

// Mirrors protocol.RuntimeManifestPack. RuntimeManifestPack 是清单里的一个包。 它刻意**不含**可执行文件路径、PATH 目录、环境变量：那些是"本机要执行什么"， 由客户端按 id 与平台自己决定（见 desktop/runtimepack.go）。清单能改的只有 "下哪个文件"，不能改"跑哪个文件"。
export interface RuntimeManifestPack {
  id: string;
  version: string;
  url: string;
  sha256: string;
  size: number;
  notes: string;
}

// Mirrors protocol.RuntimePack. RuntimePack 是一个运行时包此刻的全部状态：托管包装没装、系统里有没有、能不能用。
export interface RuntimePack {
  id: RuntimePackId;
  label: string;
  summary: string;
  stage: RuntimeStage;
  version: string;
  available: string;
  size: number;
  received: number;
  error: string;
  systemPath: string;
  systemVersion: string;
  systemUsable: boolean;
  minVersion: string;
  active: string;
  needsAuthorize: boolean;
}

// Mirrors protocol.SaveCustomModelRequest. SaveCustomModelRequest 新增或修改一个自定义模型。编辑时 OriginalName 定位旧 记录；APIKey 留空表示保留旧密钥，ClearAPIKey 才显式清除，两者不能同时使用。
export interface SaveCustomModelRequest {
  originalName?: string;
  name: string;
  provider?: string;
  model: string;
  baseURL: string;
  authMode?: string;
  apiKey?: string;
  clearAPIKey?: boolean;
}

// Mirrors protocol.SecretStorage. SecretStorage 报告本机能不能安全保存登录状态。 凭据保护在取不到系统钥匙串时**故意不落盘**（理由见 desktop/secret_keyring.go）。 这个取舍是对的，但此前它是全静默的——用户看到的只有"怎么每次都要重新登录"， 而真正的原因可能只是少装了一个包。这三个字段就是为了把那句话说出来。
export interface SecretStorage {
  ok: boolean;
  reason?: string;
  fix?: string;
}

// Mirrors protocol.SessionInfo. SessionInfo is the display state returned when a session starts and by Status.
export interface SessionInfo {
  sessionId: string;
  model: string;
  cwd: string;
  permissionMode: string;
  planMode: boolean;
  reasoningScenario: string;
  thinkingEffort: string;
  maxContextTokens: number;
  inputPricePerMTok: number;
  outputPricePerMTok: number;
  pricingSource: string;
  previewBaseURL: string;
}

// Mirrors protocol.SessionRenamed. SessionRenamed announces a session's freshly generated title.
export interface SessionRenamed {
  id: string;
  title: string;
}

// Mirrors protocol.SessionSummary. SessionSummary describes a saved session for the sidebar's recent list.
export interface SessionSummary {
  id: string;
  title: string;
  when: string;
  turns: number;
}

// Mirrors protocol.SkillInfo. SkillInfo is one project skill for the UI's skill manager.
export interface SkillInfo {
  name: string;
  displayName: string;
  displayDescription: string;
  description: string;
  body: string;
  source: string;
  path: string;
  editable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.SkillInstallProgress. SkillInstallProgress 是一次安装的实时进度。 它报的是**真的发生了什么**，不是按定时器推的假进度：Stage 由各步骤自己发， Received/Total 来自 HTTP 响应体的实际字节数与 Content-Length。假进度条在快的 时候显得慢、在卡住的时候还在动，等于把唯一能判断"是不是死了"的信号也抹掉。
export interface SkillInstallProgress {
  id: number;
  name: string;
  stage: string;
  received: number;
  total: number;
}

// Mirrors protocol.SkillList. SkillList is the skill manager's view: loaded skills plus load problems.
export interface SkillList {
  skills: SkillInfo[] | null;
  problems: SkillProblem[] | null;
}

// Mirrors protocol.SkillLoad. SkillLoad is what the desktop's Skill tool attaches to its progress event's `data` when the model loads a skill, so the chat can render a card naming what was loaded instead of a bare "加载技能" row.
export interface SkillLoad {
  name: string;
  description: string;
  source: string;
  dir: string;
  truncated?: boolean;
}

// Mirrors protocol.SkillMarketPage. SkillMarketPage 是市场页一次要画的全部东西。 Categories 由这一批技能的 category 去重得来，而不是另开一个接口：上游没有分类 接口，分类本来就只是技能表里的一列，从数据里长出来的页签永远和内容对得上。
export interface SkillMarketPage {
  skills: MarketSkill[] | null;
  categories: string[] | null;
  total: number;
  fetchedAt: string;
}

// Mirrors protocol.SkillProblem. SkillProblem reports a skill directory that failed to load.
export interface SkillProblem {
  dir: string;
  reason: string;
}

// Mirrors protocol.SkillSaveRequest. SkillSaveRequest creates or updates a skill.
export interface SkillSaveRequest {
  originalName: string;
  name: string;
  displayName: string;
  displayDescription: string;
  description: string;
  body: string;
  scope: string;
}

// Mirrors protocol.StartRecordingRequest. StartRecordingRequest 开一场录音。空字段一律回落到 RecorderSettings 里存的值。
export interface StartRecordingRequest {
  title: string;
  lang: string;
  micDeviceId: string;
  sysDeviceId: string;
}

// Mirrors protocol.StartSessionRequest. StartSessionRequest opens a session for a workspace.
export interface StartSessionRequest {
  cwd: string;
  provider: string;
  model: string;
  customModelName?: string;
  tenantId: string;
  baseURL: string;
  apiKey: string;
  authToken: string;
  apiKeyProtected?: string;
  authTokenProtected?: string;
  permissionMode: string;
  reasoningScenario: string;
  thinkingEffort: string;
  harmJudgeModel: string;
  harmJudgeVotes: number;
  maxTokens: number;
  maxContextTokens: number;
  maxHistoryMessages: number;
  resume: string;
  continue: boolean;
  recentWorkspaces?: string[] | null;
  customModels?: CustomModel[] | null;
  webProxy?: string;
  skipLogin?: boolean;
  contextAudit?: boolean;
}

// Mirrors protocol.ToolEvent. ToolEvent is the wire form of one tool-lifecycle update.
export interface ToolEvent {
  type: ToolEventType;
  toolName?: string;
  toolUseID?: string;
  parentToolUseID?: string;
  agentName?: string;
  input?: unknown;
  message?: string;
  data?: unknown;
  files?: FileReference[] | null;
  filesTotal?: number;
  output?: OutputLine[] | null;
  outputTotal?: number;
  outputTruncated?: boolean;
  image?: ResultImage;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

// Mirrors protocol.ToolInfo. ToolInfo is a tool's name and description for the @-mention picker.
export interface ToolInfo {
  name: string;
  description: string;
  source: string;
  server?: string;
  concurrencySafe: boolean;
  toggleable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.TurnEnd. TurnEnd summarizes a completed turn.
export interface TurnEnd {
  text: string;
  stopReason: string;
  iterations: number;
  toolResultCount: number;
  inputTokens: number;
  outputTokens: number;
  contextTokens: number;
  contextTokensSaved?: number;
  stopped: boolean;
  durationMs?: number;
}

// Mirrors protocol.TurnError. TurnError reports a failed or interrupted turn.
export interface TurnError {
  error: string;
}

// Mirrors protocol.TurnQueued. TurnQueued announces that a submitted turn is waiting for a concurrency slot.
export interface TurnQueued {
}

// Mirrors protocol.UpdateInfo. UpdateInfo 是更新器的完整状态，也是唯一的对外形状。 它同时是 UpdateStatus()（纯读，不联网）的返回值和 EventUpdate 的载荷：读一次拿到 的东西和后续推送过来的东西是同一种，前端不必为「初始态」和「更新态」写两套解析。
export interface UpdateInfo {
  current: string;
  stage: UpdateStage;
  latest: string;
  notes: string;
  publishedAt: string;
  size: number;
  received: number;
  checkedAt: string;
  error: string;
  installError: string;
  canInstall: boolean;
  file: string;
  autoRestart: boolean;
}

// Mirrors protocol.Warning. Warning is a non-fatal diagnostic surfaced to the UI.
export interface Warning {
  message: string;
}
