// Code generated by protogen. DO NOT EDIT.
//
// Mirrors the Go wire protocol (agentloop's protocol package) and the
// desktop.App command surface (internal/desktop).
// Regenerate with: go run ./tools/protogen

// Mirrors protocol.Version. Version is the protocol's single monotonically increasing version number.
export const ProtocolVersion = 1;

// Mirrors the protocol.Event* constants. Event names emitted by the host; payload types are mapped in events.ts.
export const Events = {
  AssistantDelta: 'assistant:delta',
  AssistantThinking: 'assistant:thinking',
  ContextUsage: 'context:usage',
  HarmAutoAllow: 'harm:autoallow',
  PassportChanged: 'passport:changed',
  PermissionRequest: 'permission:request',
  PlanUpdated: 'plan:updated',
  RecorderLevel: 'recorder:level',
  RecorderState: 'recorder:state',
  RecorderTranscript: 'recorder:transcript',
  Retry: 'llm:retry',
  SessionRenamed: 'session:renamed',
  ToolEvent: 'tool:event',
  TurnEnd: 'turn:end',
  TurnError: 'turn:error',
  TurnQueued: 'turn:queued',
  Warning: 'warning',
} as const;

// EventName is the union of known event names.
export type EventName = (typeof Events)[keyof typeof Events];

// Mirrors the protocol.ToolEvent* constants. Tool event types, the discriminator values of ToolEvent.type.
export const ToolEventTypes = {
  AgentDelta: 'agent_delta',
  AgentUsage: 'agent_usage',
  Completed: 'completed',
  Failed: 'failed',
  Output: 'output',
  Progress: 'progress',
  Started: 'started',
} as const;

// ToolEventType keeps unknown discriminators assignable so a newer host degrades gracefully.
export type ToolEventType = (typeof ToolEventTypes)[keyof typeof ToolEventTypes] | (string & {});

// Mirrors the protocol.Decision* constants. Decision values a client passes to resolvePermission; the host fails closed on anything else.
export const Decisions = {
  AllowOnce: 'allow-once',
  AllowProject: 'allow-project',
  AllowSession: 'allow-session',
  Deny: 'deny',
} as const;

// Decision keeps unknown values assignable; the host treats them as deny.
export type Decision = (typeof Decisions)[keyof typeof Decisions] | (string & {});

// Mirrors the protocol.ErrCode* constants. Error codes carried by protocol.Error; clients switch on code.
export const ErrCodes = {
  Busy: 'busy',
  Internal: 'internal',
  InvalidArgument: 'invalid_argument',
  NoSession: 'no_session',
  NotFound: 'not_found',
  NotLoggedIn: 'not_logged_in',
  Unavailable: 'unavailable',
} as const;

// ErrCode keeps unknown codes assignable so a newer host degrades gracefully.
export type ErrCode = (typeof ErrCodes)[keyof typeof ErrCodes] | (string & {});

// Mirrors the protocol.PlanStage* constants. Stages of 计划模式's planning pipeline, in order; the values of plan_write's stage argument.
export const PlanStages = {
  Design: 'design',
  Review: 'review',
  Understanding: 'understanding',
} as const;

// PlanStage is the closed set of planning stages — the shell's own pipeline, so an unknown value is a bug, not a newer peer.
export type PlanStage = (typeof PlanStages)[keyof typeof PlanStages];

// Mirrors the protocol.PlanState* constants. Lifecycle states of a planning run, carried by PlanRun.state.
export const PlanStates = {
  AwaitingApproval: 'awaiting_approval',
  Cancelled: 'cancelled',
  Executing: 'executing',
  Idle: 'idle',
  Planning: 'planning',
} as const;

// PlanState is the closed set of planning-run states.
export type PlanState = (typeof PlanStates)[keyof typeof PlanStates];

// Mirrors protocol.AgentInfo. AgentInfo is one sub-agent for the UI's sub-agent manager.
export interface AgentInfo {
  name: string;
  description: string;
  tools: string;
  model: string;
  prompt: string;
  source: string;
  path: string;
  editable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.AgentList. AgentList is the sub-agent manager's view: loaded agents plus load problems.
export interface AgentList {
  agents: AgentInfo[] | null;
  problems: AgentProblem[] | null;
}

// Mirrors protocol.AgentProblem. AgentProblem reports a sub-agent file that failed to load.
export interface AgentProblem {
  path: string;
  reason: string;
}

// Mirrors protocol.AgentSaveRequest. AgentSaveRequest creates or updates a sub-agent.
export interface AgentSaveRequest {
  originalName: string;
  name: string;
  description: string;
  tools: string;
  model: string;
  prompt: string;
  scope: string;
}

// Mirrors protocol.ApprovalSummary. ApprovalSummary is the display-oriented classification of an action awaiting approval.
export interface ApprovalSummary {
  toolName?: string;
  operation?: string;
  risk?: string;
  resourceTypes?: string[] | null;
  resourceScope?: string;
  resourceCount?: number;
  mutationKind?: string;
  outsideWorkspace?: boolean;
  commandCategory?: string;
  commandSummary?: string;
  networkHost?: string;
  mcpServer?: string;
  mcpTool?: string;
  policyRule?: string;
}

// Mirrors protocol.AssistantDelta. AssistantDelta is one streamed text fragment from the model.
export interface AssistantDelta {
  text: string;
}

// Mirrors protocol.CompactResult. CompactResult reports the in-memory message counts before and after an explicit compaction.
export interface CompactResult {
  before: number;
  after: number;
  contextTokens: number;
  inputTokens: number;
  outputTokens: number;
}

// Mirrors protocol.ContextAuditInfo. ContextAuditInfo 是"上下文审核"（仅测试版构建存在）的状态快照。开启后，引擎每次 发给模型的完整请求上下文（系统提示词、全部消息历史、工具清单）都会落盘，并由一个 仅监听 127.0.0.1 的本地页面提供查看。
export interface ContextAuditInfo {
  supported: boolean;
  enabled: boolean;
  url: string;
  dir: string;
}

// Mirrors protocol.ContextUsage. ContextUsage reports how full the context window is right now, emitted before each model round-trip inside a turn.
export interface ContextUsage {
  contextTokens: number;
  maxContextTokens: number;
  iteration: number;
}

// Mirrors protocol.CustomModel. CustomModel 是用户自定义的直连模型接入点，与通行证平台模型并列显示在模型 选择器里。Provider 是引擎 provider registry 的名称（当前为 openai/ openai-responses/anthropic），由 llm.IsRegistered 校验而非本仓库的名单；旧配置 没有该字段时由桌面端按 openai 兼容处理。密钥字段仅用于桌面端持久化， ListCustomModels 对外返回时必须清空，只通过 HasAPIKey 暴露是否已配置。
export interface CustomModel {
  name: string;
  provider?: string;
  model: string;
  baseURL: string;
  hasAPIKey?: boolean;
  apiKey?: string;
  apiKeyProtected?: string;
}

// Mirrors protocol.EditDiff. EditDiff is the red/green review of one edit: the turn baseline vs the turn's latest content for that file, as renderable diff lines.
export interface EditDiff {
  relPath: string;
  created: boolean;
  lines: OutputLine[] | null;
}

// Mirrors protocol.EditRecord. EditRecord is the per-edit metadata attached to a Write/Edit tool event's Data (live) and returned by ListEdits (resume).
export interface EditRecord {
  snapshotId: string;
  toolUseId: string;
  relPath: string;
  added: number;
  removed: number;
  created: boolean;
  reverted?: boolean;
}

// Mirrors protocol.Envelope. Envelope wraps every event on the wire with its addressing and ordering metadata, so the same event stream works over any transport: in-process bindings today, a multiplexed WebSocket tomorrow.
export interface Envelope<P = unknown> {
  event: string;
  sessionId?: string;
  seq: number;
  ts: string;
  payload: P;
}

// Mirrors protocol.Error. Error is the wire form of a command failure.
export interface Error {
  code: ErrCode;
  message: string;
  details?: Record<string, string> | null;
}

// Mirrors protocol.FileReference. FileReference is a sanitized, workspace-relative file reference for UI progress summaries.
export interface FileReference {
  path: string;
  kind?: string;
}

// Mirrors protocol.HarmAutoAllow. HarmAutoAllow is the payload of EventHarmAutoAllow: a sanitized record of a harm-gate decision (no raw command or path).
export interface HarmAutoAllow {
  tool: string;
  toolUseID: string;
  operation: string;
  risk: string;
  reason: string;
  outcome: string;
  count: number;
}

// Mirrors protocol.Info. Info is the handshake payload describing the host's protocol support.
export interface Info {
  protocolVersion: number;
  appVersion?: string;
}

// Mirrors protocol.MCPServerInfo. MCPServerInfo is one configured MCP server plus its live connection state, for the UI's MCP management page.
export interface MCPServerInfo {
  name: string;
  transport: string;
  command?: string;
  args?: string[] | null;
  env?: Record<string, string> | null;
  dir?: string;
  url?: string;
  headers?: Record<string, string> | null;
  passport: boolean;
  enabled: boolean;
  connected: boolean;
  toolCount: number;
  tools?: MCPToolBrief[] | null;
}

// Mirrors protocol.MCPServerInput. MCPServerInput is the payload for creating or updating a server.
export interface MCPServerInput {
  originalName: string;
  name: string;
  transport: string;
  command: string;
  args: string[] | null;
  env: Record<string, string> | null;
  dir: string;
  url: string;
  headers: Record<string, string> | null;
  passport: boolean;
  enabled: boolean;
}

// Mirrors protocol.MCPToolBrief. MCPToolBrief is one tool a connected MCP server exposes, for listing a server's capabilities on the MCP page.
export interface MCPToolBrief {
  name: string;
  description?: string;
}

// Mirrors protocol.McpMarketEntry. McpMarketEntry is one installable MCP server from the platform market (bridge GET /api/mcp/market).
export interface McpMarketEntry {
  id: string;
  name: string;
  description?: string;
  transport: string;
  url: string;
  passport: boolean;
  official: boolean;
}

// Mirrors protocol.MemoryInfo. MemoryInfo is the agent's persistent memory, split by scope.
export interface MemoryInfo {
  user: string[] | null;
  project: string[] | null;
}

// Mirrors protocol.OutputLine. OutputLine is a single sanitized, bounded line of tool output for UI display.
export interface OutputLine {
  stream?: string;
  text: string;
}

// Mirrors protocol.PassportModel. PassportModel 是 Bridge /v1/models 列表项。
export interface PassportModel {
  id: string;
  ownedBy: string;
}

// Mirrors protocol.PassportStatus. PassportStatus 是前端展示用的登录态 + 用户信息。
export interface PassportStatus {
  loggedIn: boolean;
  userId?: string;
  userName?: string;
  name?: string;
  nickname?: string;
  avatar?: string;
  tenantId?: string;
}

// Mirrors protocol.PassportTenant. PassportTenant 是当前用户可用的租户（Bridge /api/tenants）。 ParentID 供前端渲染层级树；父租户可能不在用户的可用列表里 （用户只被授了子级），前端须把这类节点当根渲染，不能丢弃。
export interface PassportTenant {
  id: string;
  name: string;
  parentId?: string;
}

// Mirrors protocol.PermissionRequest. PermissionRequest asks the user to approve or deny one pending action.
export interface PermissionRequest {
  id: string;
  summary: ApprovalSummary;
  targets?: string[] | null;
  externalTargets?: string[] | null;
  externalRoots?: string[] | null;
  command?: string;
  harmReason?: string;
  samplingServer?: string;
  allowedDecisions?: string[] | null;
}

// Mirrors protocol.PlanApproveRequest. PlanApproveRequest 是用户点"确认执行"时提交的东西：编辑后的最终清单，加上执行阶段 要切换到的权限模式（沿用原先那张三选一卡片的语义：交互 / 智能）。
export interface PlanApproveRequest {
  doc: PlanDoc;
  permissionMode: string;
}

// Mirrors protocol.PlanApproveResult. PlanApproveResult 把审批的两件后果一起带回前端：会话状态已变（计划模式关、权限模式 切好），以及应当作为下一条消息发出去的执行指令。指令由后端拼是为了让措辞与清单编号 只有一个来源（也便于单测），发送仍走前端既有的 send 路径，这样 busy、用户气泡、回合 生命周期全部复用原有链路。
export interface PlanApproveResult {
  info: SessionInfo;
  executionPrompt: string;
}

// Mirrors protocol.PlanDoc. PlanDoc 是规划文档本身：三个阶段各自往里填一部分，用户在审批前还能改。
export interface PlanDoc {
  goal?: string;
  nonGoals?: string[] | null;
  title?: string;
  steps?: PlanStep[] | null;
  risks?: string[] | null;
  questions?: string[] | null;
  reviewNotes?: string[] | null;
}

// Mirrors protocol.PlanRun. PlanRun 是一次规划运行的完整对外状态，EventPlanUpdated 与 PlanStatus 都发它。
export interface PlanRun {
  state: PlanState;
  stage?: PlanStage;
  doc?: PlanDoc;
  edited?: boolean;
  updatedAt?: string;
}

// Mirrors protocol.PlanStep. PlanStep 是清单里的一步。ID 由外壳分配并在编辑往返中保持稳定（前端拿它做 key， 后端拿它认"这步是不是新加的"）；模型不提供 ID，新步骤留空由后端补。
export interface PlanStep {
  id: string;
  title: string;
  detail?: string;
  files?: string[] | null;
}

// Mirrors protocol.ProjectContextInfo. ProjectContextInfo is the workspace's project-instructions file (RUNCODE.md or CLAUDE.md), for viewing and editing.
export interface ProjectContextInfo {
  path: string;
  name: string;
  content: string;
  exists: boolean;
}

// Mirrors protocol.RecorderDevice. RecorderDevice 是「麦克风 ∨」下拉里的一项。
export interface RecorderDevice {
  id: string;
  name: string;
  isDefault: boolean;
}

// Mirrors protocol.RecorderDeviceList. RecorderDeviceList 是两路音源各自可选的设备。 Supported=false 表示这台机器上根本开不了录音（非 Windows、或 WASAPI 初始化 失败）。分开报而不是直接返回 error：界面要把「录音纪要」入口置灰并给出理由， 而不是等用户点下去才弹一个错。
export interface RecorderDeviceList {
  mic: RecorderDevice[] | null;
  sys: RecorderDevice[] | null;
  supported: boolean;
  reason?: string;
}

// Mirrors protocol.RecorderLevel. RecorderLevel 是两条轨的实时电平（0..1），约 20 Hz。 两条轨合成一条事件发：它们各自约 20 Hz，分开发就是 40 次/秒的事件，而界面 上是同一次重绘要用的两个数。
export interface RecorderLevel {
  mic: number;
  sys: number;
}

// Mirrors protocol.RecorderSettings. RecorderSettings 是录音纪要的客户端设置，落在配置目录里，与会话无关。
export interface RecorderSettings {
  gatewayUrl: string;
  gatewayToken: string;
  speakerName: string;
  lang: string;
  micDiarize: boolean;
  micDeviceId: string;
  sysDeviceId: string;
  keepAudio: boolean;
  summaryModel: string;
  root?: string;
}

// Mirrors protocol.RecorderState. RecorderState 是录音状态的变化。
export interface RecorderState {
  id: string;
  state: string;
  audioMs: number;
  uplink?: string;
  error?: string;
}

// Mirrors protocol.RecorderTrack. RecorderTrack 是一条音轨录完后的记录。
export interface RecorderTrack {
  source: string;
  wav: string;
  sampleRate: number;
  channels: number;
  durationMs: number;
  gapMs: number;
  sentFrames: number;
  droppedFrames: number;
  reconnects: number;
}

// Mirrors protocol.RecorderTranscript. RecorderTranscript 是网关下行的一条转写事件。 字段与 recorder.Event 一一对应，含义见那边——这里刻意不复述，两处各写一遍 只会各自漂移。
export interface RecorderTranscript {
  type: string;
  track?: string;
  seg: number;
  rev: number;
  text?: string;
  bt?: number;
  et?: number;
  spk?: string;
  name?: string;
  userId?: string;
  conf?: number;
  segs?: number[] | null;
  silence?: number;
  need?: number;
  stage?: string;
  queuePos?: number;
}

// Mirrors protocol.RecordingInfo. RecordingInfo 是一场录音在界面上的样子。ID 为空表示「当前没有录音」。
export interface RecordingInfo {
  id: string;
  title: string;
  room: string;
  state: string;
  lang?: string;
  startedAt: string;
  endedAt?: string;
  audioMs: number;
  interrupted?: boolean;
  transcript?: string;
  needsBackfill?: boolean;
  tracks?: RecorderTrack[] | null;
  uplink?: string;
  dir?: string;
}

// Mirrors protocol.ResultImage. ResultImage is an inline image a tool returned (Data is base64 in JSON).
export interface ResultImage {
  media_type?: string;
  data?: string;
  url?: string;
}

// Mirrors protocol.ResumedBlock. ResumedBlock is one rendered item of a reopened conversation.
export interface ResumedBlock {
  kind: string;
  text?: string;
  tool?: ResumedTool;
}

// Mirrors protocol.ResumedSession. ResumedSession carries a reopened session's status plus its prior conversation as rendered blocks so the frontend can repaint it.
export interface ResumedSession {
  info: SessionInfo;
  blocks: ResumedBlock[] | null;
  contextTokens: number;
}

// Mirrors protocol.ResumedTool. ResumedTool is a reconstructed tool step.
export interface ResumedTool {
  toolName: string;
  toolUseId: string;
  path?: string;
  input?: string;
  isError: boolean;
  output?: string;
}

// Mirrors protocol.RetryNotice. RetryNotice reports that an LLM request failed transiently and is being retried.
export interface RetryNotice {
  reason: string;
  attempt: number;
  maxAttempts: number;
}

// Mirrors protocol.SaveCustomModelRequest. SaveCustomModelRequest 新增或修改一个自定义模型。编辑时 OriginalName 定位旧 记录；APIKey 留空表示保留旧密钥，ClearAPIKey 才显式清除，两者不能同时使用。
export interface SaveCustomModelRequest {
  originalName?: string;
  name: string;
  provider?: string;
  model: string;
  baseURL: string;
  apiKey?: string;
  clearAPIKey?: boolean;
}

// Mirrors protocol.SessionInfo. SessionInfo is the display state returned when a session starts and by Status.
export interface SessionInfo {
  sessionId: string;
  model: string;
  cwd: string;
  permissionMode: string;
  planMode: boolean;
  reasoningScenario: string;
  thinkingEffort: string;
  maxContextTokens: number;
  inputPricePerMTok: number;
  outputPricePerMTok: number;
  pricingSource: string;
  previewBaseURL: string;
}

// Mirrors protocol.SessionRenamed. SessionRenamed announces a session's freshly generated title.
export interface SessionRenamed {
  id: string;
  title: string;
}

// Mirrors protocol.SessionSummary. SessionSummary describes a saved session for the sidebar's recent list.
export interface SessionSummary {
  id: string;
  title: string;
  when: string;
  turns: number;
}

// Mirrors protocol.SkillInfo. SkillInfo is one project skill for the UI's skill manager.
export interface SkillInfo {
  name: string;
  description: string;
  body: string;
  source: string;
  path: string;
  editable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.SkillList. SkillList is the skill manager's view: loaded skills plus load problems.
export interface SkillList {
  skills: SkillInfo[] | null;
  problems: SkillProblem[] | null;
}

// Mirrors protocol.SkillLoad. SkillLoad is what the desktop's Skill tool attaches to its progress event's `data` when the model loads a skill, so the chat can render a card naming what was loaded instead of a bare "加载技能" row.
export interface SkillLoad {
  name: string;
  description: string;
  source: string;
  dir: string;
  truncated?: boolean;
}

// Mirrors protocol.SkillProblem. SkillProblem reports a skill directory that failed to load.
export interface SkillProblem {
  dir: string;
  reason: string;
}

// Mirrors protocol.SkillSaveRequest. SkillSaveRequest creates or updates a skill.
export interface SkillSaveRequest {
  originalName: string;
  name: string;
  description: string;
  body: string;
  scope: string;
}

// Mirrors protocol.StartRecordingRequest. StartRecordingRequest 开一场录音。空字段一律回落到 RecorderSettings 里存的值。
export interface StartRecordingRequest {
  title: string;
  lang: string;
  micDeviceId: string;
  sysDeviceId: string;
}

// Mirrors protocol.StartSessionRequest. StartSessionRequest opens a session for a workspace.
export interface StartSessionRequest {
  cwd: string;
  provider: string;
  model: string;
  customModelName?: string;
  tenantId: string;
  baseURL: string;
  apiKey: string;
  authToken: string;
  apiKeyProtected?: string;
  authTokenProtected?: string;
  permissionMode: string;
  reasoningScenario: string;
  thinkingEffort: string;
  harmJudgeModel: string;
  harmJudgeVotes: number;
  maxTokens: number;
  maxContextTokens: number;
  maxHistoryMessages: number;
  resume: string;
  continue: boolean;
  recentWorkspaces?: string[] | null;
  customModels?: CustomModel[] | null;
  webProxy?: string;
  skipLogin?: boolean;
  contextAudit?: boolean;
}

// Mirrors protocol.ToolEvent. ToolEvent is the wire form of one tool-lifecycle update.
export interface ToolEvent {
  type: ToolEventType;
  toolName?: string;
  toolUseID?: string;
  parentToolUseID?: string;
  agentName?: string;
  input?: unknown;
  message?: string;
  data?: unknown;
  files?: FileReference[] | null;
  filesTotal?: number;
  output?: OutputLine[] | null;
  outputTotal?: number;
  outputTruncated?: boolean;
  image?: ResultImage;
  inputTokens?: number;
  outputTokens?: number;
  durationMs?: number;
}

// Mirrors protocol.ToolInfo. ToolInfo is a tool's name and description for the @-mention picker.
export interface ToolInfo {
  name: string;
  description: string;
  source: string;
  server?: string;
  concurrencySafe: boolean;
  toggleable: boolean;
  disabledUser: boolean;
  disabledProject: boolean;
}

// Mirrors protocol.TurnEnd. TurnEnd summarizes a completed turn.
export interface TurnEnd {
  text: string;
  stopReason: string;
  iterations: number;
  toolResultCount: number;
  inputTokens: number;
  outputTokens: number;
  contextTokens: number;
  contextTokensSaved?: number;
  stopped: boolean;
  durationMs?: number;
}

// Mirrors protocol.TurnError. TurnError reports a failed or interrupted turn.
export interface TurnError {
  error: string;
}

// Mirrors protocol.TurnQueued. TurnQueued announces that a submitted turn is waiting for a concurrency slot.
export interface TurnQueued {
}

// Mirrors protocol.Warning. Warning is a non-fatal diagnostic surfaced to the UI.
export interface Warning {
  message: string;
}
