package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

const header = `// Code generated by protogen. DO NOT EDIT.
//
// Mirrors the Go wire protocol (agentloop's protocol package) and the
// desktop.App command surface (internal/desktop).
// Regenerate with: go run ./tools/protogen
`

// emitTypes renders types.ts: constant groups and one interface per protocol struct.
func emitTypes(m *model) []byte {
	var b bytes.Buffer
	b.WriteString(header)

	b.WriteString("\n// Mirrors protocol.Version.")
	if m.versionDoc != "" {
		b.WriteString(" " + m.versionDoc)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "export const ProtocolVersion = %d;\n", m.version)

	for _, g := range m.groups {
		fmt.Fprintf(&b, "\n// Mirrors the protocol.%s* constants. %s\n", g.spec.goPrefix, g.spec.doc)
		fmt.Fprintf(&b, "export const %s = {\n", g.spec.constName)
		for _, it := range g.items {
			fmt.Fprintf(&b, "  %s: %s,\n", it.key, tsString(it.value))
		}
		b.WriteString("} as const;\n")
		fmt.Fprintf(&b, "\n// %s\n", g.spec.unionDoc)
		fmt.Fprintf(&b, "export type %s = (typeof %s)[keyof typeof %s]", g.spec.unionName, g.spec.constName, g.spec.constName)
		if g.spec.open {
			b.WriteString(" | (string & {})")
		}
		b.WriteString(";\n")
	}

	for _, s := range m.structs {
		fmt.Fprintf(&b, "\n// Mirrors protocol.%s.", s.name)
		if s.doc != "" {
			b.WriteString(" " + s.doc)
		}
		b.WriteString("\n")
		fmt.Fprintf(&b, "export interface %s%s {\n", s.name, s.typeParams)
		for _, f := range s.fields {
			opt := ""
			if f.optional {
				opt = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", tsPropName(f.name), opt, f.tsType)
		}
		b.WriteString("}\n")
	}
	return b.Bytes()
}

// emitEvents renders events.ts: the EventMap and the typed subscription helpers.
func emitEvents(m *model) []byte {
	var b bytes.Buffer
	b.WriteString(header)

	imports := map[string]bool{"Envelope": true}
	for _, e := range m.events {
		imports[e.payload] = true
	}
	fmt.Fprintf(&b, "\nimport type { %s } from './types';\n", strings.Join(sortedKeys(imports), ", "))

	b.WriteString("\n// EventMap maps every wire event name to its payload type.\n")
	b.WriteString("export interface EventMap {\n")
	for _, e := range m.events {
		fmt.Fprintf(&b, "  %s: %s;\n", tsString(e.wire), e.payload)
	}
	b.WriteString("}\n")

	b.WriteString(`
const runtime = () => (window as any).runtime;

// onEvent subscribes to a host event and delivers its typed payload.
// It returns an unsubscribe function.
export function onEvent<K extends keyof EventMap>(name: K, cb: (payload: EventMap[K]) => void): () => void {
  return runtime().EventsOn(name, (env: Envelope<EventMap[K]>) => cb(env.payload));
}

// onEnvelope subscribes to a host event and delivers the full envelope
// (sessionId, seq, ts plus the typed payload). It returns an unsubscribe function.
export function onEnvelope<K extends keyof EventMap>(name: K, cb: (env: Envelope<EventMap[K]>) => void): () => void {
  return runtime().EventsOn(name, (env: Envelope<EventMap[K]>) => cb(env));
}
`)
	return b.Bytes()
}

// emitCommands renders commands.ts: one typed wrapper per App command.
func emitCommands(m *model) []byte {
	var b bytes.Buffer
	b.WriteString(header)

	imports := map[string]bool{}
	for _, c := range m.commands {
		for _, name := range referencedTypes(c) {
			imports[name] = true
		}
	}
	if len(imports) > 0 {
		fmt.Fprintf(&b, "\nimport type { %s } from './types';\n", strings.Join(sortedKeys(imports), ", "))
	}

	b.WriteString(`
// app resolves the Wails binding for desktop.App lazily, so importing this
// module before the runtime injects window.go is safe.
const app = () => (window as any).go.desktop.App;
`)

	for _, c := range m.commands {
		b.WriteString("\n")
		if c.doc != "" {
			fmt.Fprintf(&b, "// %s\n", c.doc)
		}
		fmt.Fprintf(&b, "// kind: %s\n", c.kind)
		var params, args []string
		for _, p := range c.params {
			params = append(params, p.name+": "+p.tsType)
			args = append(args, p.name)
		}
		fmt.Fprintf(&b, "export function %s(%s): Promise<%s> {\n", c.tsName, strings.Join(params, ", "), c.result)
		fmt.Fprintf(&b, "  return app().%s(%s);\n", c.goName, strings.Join(args, ", "))
		b.WriteString("}\n")
	}
	return b.Bytes()
}

// referencedTypes lists the protocol interface names a command's signature uses.
func referencedTypes(c commandDef) []string {
	set := map[string]bool{}
	collect := func(tsType string) {
		for _, tok := range strings.FieldsFunc(tsType, func(r rune) bool {
			return !(r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9')
		}) {
			switch tok {
			case "string", "number", "boolean", "void", "null", "unknown", "Record":
				continue
			}
			set[tok] = true
		}
	}
	for _, p := range c.params {
		collect(p.tsType)
	}
	collect(c.result)
	keys := make([]string, 0, len(set))
	for k := range set {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// tsString renders a single-quoted TS string literal.
func tsString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "'", `\'`)
	return "'" + s + "'"
}

// tsPropName quotes an interface property name when it is not a plain identifier.
func tsPropName(s string) string {
	if s == "" {
		return tsString(s)
	}
	for i, r := range s {
		ok := r == '_' || r == '$' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return tsString(s)
		}
	}
	return s
}
