// Code generated by protogen. DO NOT EDIT.
//
// Mirrors the Go wire protocol (agentloop's protocol package) and the
// desktop.App command surface (internal/desktop).
// Regenerate with: go run ./tools/protogen

import type { AssistantDelta, Envelope, HarmAutoAllow, PassportStatus, PermissionRequest, SessionRenamed, ToolEvent, TurnEnd, TurnError, TurnQueued, Warning } from './types';

// EventMap maps every wire event name to its payload type.
export interface EventMap {
  'assistant:delta': AssistantDelta;
  'assistant:thinking': AssistantDelta;
  'harm:autoallow': HarmAutoAllow;
  'passport:changed': PassportStatus;
  'permission:request': PermissionRequest;
  'session:renamed': SessionRenamed;
  'tool:event': ToolEvent;
  'turn:end': TurnEnd;
  'turn:error': TurnError;
  'turn:queued': TurnQueued;
  'warning': Warning;
}

const runtime = () => (window as any).runtime;

// onEvent subscribes to a host event and delivers its typed payload.
// It returns an unsubscribe function.
export function onEvent<K extends keyof EventMap>(name: K, cb: (payload: EventMap[K]) => void): () => void {
  return runtime().EventsOn(name, (env: Envelope<EventMap[K]>) => cb(env.payload));
}

// onEnvelope subscribes to a host event and delivers the full envelope
// (sessionId, seq, ts plus the typed payload). It returns an unsubscribe function.
export function onEnvelope<K extends keyof EventMap>(name: K, cb: (env: Envelope<EventMap[K]>) => void): () => void {
  return runtime().EventsOn(name, (env: Envelope<EventMap[K]>) => cb(env));
}
